export const theme = {
  candidate: {
    name: "Candace Calloway",
    displayName: "Candace Calloway",
    party: "Democratic",
    office: "State House Representative",
    district: "NW Detroit, Oak Park, Royal Oak Township",
    state: "Michigan",
    tagline: "Lead with Hope",
    primaryElectionDate: "August 4, 2026",
    generalElectionDate: "November 3, 2026",
    opponents: ["Cali Scales", "Crystal Bailey"],
    incumbent: "Regina",
    firstTimeCandidate: true,
    background: "Founded the Black Pack — outdoor organization focused on increasing Black employment in outdoor recreation and environmental conservation",
    elevatorPitch: "I am running because I believe we deserve to hope for better things and we deserve leadership that evolves. I want to represent you.",
    professionalBackground: "Construction, Education, and Urban Environmental Conservation",
    highSchool: "Andover H.S., Class of 2012",
    college: "Bowling Green State University, Class of 2016",
    communityInvolvement: [
      "Detroit Association of Women's Clubs, Inc. (DAWC)",
      "Meals on Wheels",
      "Founded The Black Pack",
    ],
    dog: { name: "Lucy", breed: "Pit Bull Terrier", includeOnEndorsements: true },
    connection: "Native Detroiter",
  },
  issues: {
    pillars: [
      {
        title: "Affordability",
        tagline: "Making Life Affordable for Every Family",
        icon: "wallet",
        priority: 1,
        color: "#0A7D3F",
        slug: "affordability",
        topics: ["Childcare costs", "Auto insurance", "Property taxes", "Post-secondary affordability", "Basic needs", "Medical care", "Utility costs"],
        heroStat: { value: "48%", label: "more for auto insurance than the national average" },
        positionSummary: "My campaign is built on a people-first, community-driven commitment: to make life affordable for everyone at all stages. I recognize that rising costs for things like medical care, insurance, property taxes, childcare, housing, utility costs and meeting basic needs are squeezing families. I commit to invest in long-term workforce solutions, expanding affordable housing opportunities and supportive resources for small businesses.",
        emotionalAngle: "Whether you're just getting started, raising a family, or enjoying retirement — costs are out of control. That changes now.",
        solutions: [
          "Fight to lower auto insurance rates for Detroit-area families",
          "Expand childcare access and affordability programs",
          "Advocate for property tax relief for homeowners",
          "Support post-secondary education affordability initiatives",
          "Invest in long-term workforce development solutions",
          "Expand affordable housing opportunities",
        ],
      },
      {
        title: "Educational Outcomes",
        tagline: "Investing in Our Children's Future",
        icon: "book-open",
        priority: 2,
        color: "#060951",
        slug: "education",
        topics: ["K-12 readiness", "Reading & math scores", "Statewide curriculum", "Trades & workforce", "College alternatives", "Early childhood & Pre-K funding", "Teacher-family-admin relationships"],
        heroStat: { value: "44th", label: "out of 50 states in 3rd grade reading" },
        positionSummary: "Everyone, regardless of background, deserves access to high-quality education in their own backyard that prepares them for a rapidly changing world. We can get there together by fostering strong relationships between teachers, family and administration and investing in early childhood and Pre-K funding.",
        emotionalAngle: "Every child in Michigan deserves a world-class education — whether their path leads to a university or a union hall.",
        solutions: [
          "Push for a statewide required reading curriculum",
          "Reverse the post-2020 decline in reading and math scores",
          "Invest in early childhood and Pre-K funding",
          "Strengthen trades and workforce development pathways",
          "Foster collaboration between teachers, families, and administration",
          "Make Michigan a top-tier education destination",
        ],
      },
      {
        title: "Safe Infrastructure Investment",
        tagline: "Building Stronger Communities",
        icon: "building",
        priority: 3,
        color: "#0D3D2B",
        slug: "infrastructure",
        topics: ["Roads & transportation", "Public transit & accessibility", "Zoning reform", "Small business support", "Affordable housing", "Existing housing repair", "Environmental protections"],
        heroStat: { value: "It's not just the roads", label: "— it's where they take us." },
        positionSummary: "I am advocating for equitable and sustainable infrastructure investment including both our roads and the places they take us to. I believe that our money is best spent on investment that promotes economic growth, improves public transportation and accessibility, provides environmental protections and allows small businesses to remain and thrive in our communities.",
        emotionalAngle: "We need to invest in our communities — not just new developments, but the neighborhoods we already call home.",
        solutions: [
          "Advocate for road and transportation improvements beyond just repairs",
          "Improve public transportation and accessibility",
          "Reform zoning laws to attract new businesses",
          "Support small businesses at city and state level",
          "Partner developers with local contractors to manage costs",
          "Invest in repairing existing housing stock, not just new builds",
          "Strengthen environmental protections in our communities",
        ],
      },
    ],
  },
  colors: {
    primary: "#060951",
    secondary: "#065124",
    accent: "#FFFFFF",
    background: "#FFFFFF",
    surface: "#F5F7FA",
    text: "#1A1A1A",
    textMuted: "#6B7280",
    pillarAffordability: "#0A7D3F",
    pillarEducation: "#060951",
    pillarInfrastructure: "#0D3D2B",
    ctaHover: "#0B0D6B",
    ctaGreen: "#087A3C",
    border: "#E2E8F0",
  },
  fonts: {
    heading: "'Inter', sans-serif",
    body: "'Inter', sans-serif",
  },
  logo: {
    type: "initials" as const,
    text: "CC",
    primaryColor: "#060951",
    secondaryColor: "#065124",
  },
  social: {
    facebook: "",
    twitter: "",
    instagram: "",
    youtube: "",
    tiktok: "",
    linkedin: "",
  },
  district: {
    communities: [
      { name: "Detroit (NW)", role: "Largest population", imageDirection: "Detroit skyline + neighborhood imagery" },
      { name: "Oak Park", role: "Highest voter turnout", imageDirection: "Stock images or photos from Candace" },
      { name: "Royal Oak Township", role: "Smallest, most disenfranchised — make them feel seen", imageDirection: "Stock images — show community investment" },
    ],
  },
  donation: {
    maxIndividualContribution: 1000,
    suggestedAmounts: [25, 50, 100, 250, 500, 1000] as number[],
    goalAmount: 50000,
    currentAmount: 0,
    showThermometer: false,
    enableRecurring: true,
    actBlueUrl: "",
    stripePublishableKey: "",
    enableApplePay: true,
    enableCashApp: true,
    enablePayPal: true,
  },
  compliance: {
    disclaimerText: "Paid for by Committee to Elect Candace Calloway",
    treasurerName: "Willie Burton",
    committeeAddress: "P.O. Box 21785, 20501 Livernois Ave, Detroit, MI 48221",
    committeeName: "Committee to Elect Candace Calloway",
    ein: "41-4169186",
    bankName: "First Independent",
    stateFilingUrl: "https://www.michigan.gov/sos/elections/disclosure/cfr",
    contributionLimitsUrl: "https://www.michigan.gov/sos/elections/disclosure/cfr/contribution-limits",
  },
  contact: {
    email: "votecandacecalloway@gmail.com",
    phone: "(313) 857-8989",
    formSubmissionsEmail: "votecandacecalloway@gmail.com",
    crm: "NGP VAN",
    googleSheets: true,
    automatedConfirmationEmails: true,
  },
  events: {
    announcementEvents: [
      { date: "March 6, 2026", location: "Detroit", type: "Campaign Announcement" },
      { date: "March 7, 2026", location: "Oak Park", type: "Campaign Announcement (tentative)" },
    ],
    estimatedFrequency: "1 per month",
    rsvpEnabled: true,
    hidePastEvents: true,
    managedBy: "Candace (self)",
  },
  endorsements: {
    confirmed: [
      { name: "Marian McClellan", title: "Oak Park Mayor", photo: "" },
      { name: "Angela Whitfield Calloway", title: "Councilwoman, District 2", photo: "" },
    ],
    includeLucy: true,
  },
} as const;

export type Theme = typeof theme;
export type Pillar = Theme['issues']['pillars'][number];
