export const theme = {
  candidate: {
    name: "Candace Calloway",
    displayName: "Candace Calloway",
    party: "Democratic",
    office: "State House Representative",
    district: "NW Detroit, Oak Park, Royal Oak Township",
    state: "Michigan",
    tagline: "Right person. Right reasons. Right time.",
    primaryElectionDate: "August 4, 2026",
    generalElectionDate: "November 3, 2026",
    opponents: ["Cali Scales", "Crystal Bailey"],
    incumbent: "Regina",
    firstTimeCandidate: true,
    background: "Construction professional for the City of Detroit. AmeriCorps/City Year alumnus. Former Academic Interventionist with DPSCD. Founded The Black Pack in 2024 to increase Black employment in outdoor recreation and environmental conservation.",
    elevatorPitch: "I am running because I believe we deserve to hope for better things and we deserve leadership that evolves. I want to represent you.",
    professionalBackground: "Construction (City of Detroit), Education (AmeriCorps City Year, DPSCD), Urban Environmental Conservation (The Nature Conservancy, The Black Pack)",
    highSchool: "Andover High School, Bloomfield Hills",
    college: "Bowling Green State University — B.S. in Applied Health Sciences",
    communityInvolvement: [
      "Detroit Association of Women's Clubs, Inc. (DAWC)",
      "Alpha Kappa Alpha Sorority, Inc. (member since 2013)",
      "AmeriCorps / City Year alumnus",
      "The Nature Conservancy — urban stormwater and flooding solutions",
      "Founded The Black Pack (2024)",
    ],
    dog: { name: "Lucy", breed: "Pit Bull Terrier", includeOnEndorsements: true },
    connection: "Native Detroiter",
  },
  issues: {
    pillars: [
      {
        title: "Affordability",
        tagline: "Making Life Affordable for Every Family",
        icon: "wallet",
        priority: 1,
        color: "#0A7D3F",
        slug: "affordability",
        topics: ["Childcare costs", "Auto insurance", "Property taxes", "Post-secondary affordability", "Basic needs", "Medical care", "Utility costs"],
        heroStat: { value: "48%", label: "more for auto insurance than the national average", link: "" },
        positionSummary: "My campaign is built on a people-first, community-driven commitment: to make life affordable for everyone at all stages. I recognize that rising costs for things like medical care, insurance, property taxes, childcare, housing, utility costs and meeting basic needs are squeezing families. I commit to invest in long-term workforce solutions, expanding affordable housing opportunities and supportive resources for small businesses.",
        emotionalAngle: "Whether you're just getting started, raising a family, or enjoying retirement — costs are out of control. That changes now.",
        solutions: [
          "Fight to lower auto insurance rates for Detroit-area families",
          "Expand childcare access and affordability programs",
          "Advocate for property tax relief for homeowners",
          "Support post-secondary education affordability initiatives",
          "Invest in long-term workforce development solutions",
          "Expand affordable housing opportunities",
        ],
      },
      {
        title: "Educational Outcomes",
        tagline: "Investing in Our Children's Future",
        icon: "book-open",
        priority: 2,
        color: "#060951",
        slug: "education",
        topics: ["K-12 readiness", "Reading & math scores", "Statewide curriculum", "Trades & workforce", "College alternatives", "Early childhood & Pre-K funding", "Teacher-family-admin relationships"],
        heroStat: { value: "1,427,386", label: "students enrolled in Michigan", link: "https://www.mischooldata.org/" },
        positionSummary: "Everyone, regardless of background, deserves access to high-quality education in their own backyard that prepares them for a rapidly changing world. We can get there together by fostering strong relationships between teachers, family and administration and investing in early childhood and Pre-K funding.",
        emotionalAngle: "Every child in Michigan deserves a world-class education — whether their path leads to a university or a union hall.",
        solutions: [
          "Push for a statewide required reading curriculum",
          "Reverse the post-2020 decline in reading and math scores",
          "Invest in early childhood and Pre-K funding",
          "Strengthen trades and workforce development pathways",
          "Foster collaboration between teachers, families, and administration",
          "Make Michigan a top-tier education destination",
        ],
      },
      {
        title: "Safe Infrastructure Investment",
        tagline: "Building Stronger Communities",
        icon: "building",
        priority: 3,
        color: "#0D3D2B",
        slug: "infrastructure",
        topics: ["Roads & transportation", "Public transit & accessibility", "Zoning reform", "Small business support", "Affordable housing", "Existing housing repair", "Environmental protections"],
        heroStat: { value: "It's not just the roads", label: "— it's where they take us.", link: "" },
        positionSummary: "I am advocating for equitable and sustainable infrastructure investment including both our roads and the places they take us to. I believe that our money is best spent on investment that promotes economic growth, improves public transportation and accessibility, provides environmental protections and allows small businesses to remain and thrive in our communities.",
        emotionalAngle: "We need to invest in our communities — not just new developments, but the neighborhoods we already call home.",
        solutions: [
          "Advocate for road and transportation improvements beyond just repairs",
          "Improve public transportation and accessibility",
          "Reform zoning laws to attract new businesses",
          "Support small businesses at city and state level",
          "Partner developers with local contractors to manage costs",
          "Invest in repairing existing housing stock, not just new builds",
          "Strengthen environmental protections in our communities",
        ],
      },
    ],
  },
  colors: {
    primary: "#060951",
    secondary: "#065124",
    accent: "#FFFFFF",
    background: "#FFFFFF",
    surface: "#F5F7FA",
    text: "#1A1A1A",
    textMuted: "#6B7280",
    pillarAffordability: "#0A7D3F",
    pillarEducation: "#060951",
    pillarInfrastructure: "#0D3D2B",
    ctaHover: "#0B0D6B",
    ctaGreen: "#087A3C",
    border: "#E2E8F0",
  },
  fonts: {
    heading: "'Inter', sans-serif",
    body: "'Inter', sans-serif",
  },
  logo: {
    type: "initials" as const,
    text: "CC",
    primaryColor: "#060951",
    secondaryColor: "#065124",
  },
  social: {
    facebook: "https://www.facebook.com/votecandacecalloway",
    twitter: "",
    instagram: "https://www.instagram.com/votecandacecalloway",
    youtube: "",
    tiktok: "",
    linkedin: "",
  },
  district: {
    communities: [
      { name: "Detroit (NW)", role: "Largest population", imageDirection: "Detroit skyline + neighborhood imagery" },
      { name: "Oak Park", role: "Highest voter turnout", imageDirection: "Stock images or photos from Candace" },
      { name: "Royal Oak Township", role: "Smallest, most disenfranchised — make them feel seen", imageDirection: "Stock images — show community investment" },
    ],
  },
  donation: {
    maxIndividualContribution: 1000,
    actBlueUrl: "https://secure.actblue.com/donate/votecandacecalloway",
  },
  compliance: {
    disclaimerText: "Paid for by Committee to Elect Candace Calloway",
    treasurerName: "",
    committeeAddress: "",
    committeeName: "Committee to Elect Candace Calloway",
    ein: "41-4169186",
    bankName: "First Independent",
    stateFilingUrl: "https://www.michigan.gov/sos/elections/disclosure/cfr",
    contributionLimitsUrl: "https://www.michigan.gov/sos/elections/disclosure/cfr/contribution-limits",
  },
  contact: {
    email: "votecandacecalloway@gmail.com",
    phone: "(313) 857-8989",
  },
  events: {
    // Events are now managed via /admin — uploaded to Supabase
    announcementEvents: [] as { date: string; time: string; location: string; venue: string; address: string; type: string; flyer: string }[],
    estimatedFrequency: "1 per month",
    hidePastEvents: true,
    managedBy: "Candace (self)",
  },
  forms: {
    contact: "",
    rsvp: "",
    volunteer: "https://forms.gle/wBcEz5F47dpjZ32w7",
    yardSign: "https://forms.gle/54EFGfDQycGzR9Ae8",
    subscribe: "",
    web3formsKey: "7f95990b-6648-49a2-b641-3c83d695a753",
  },
  media: [
    {
      id: "photo-1",
      type: "photo" as const,
      src: "/images/media/20260507_184134.jpg",
    },
    {
      id: "photo-2",
      type: "photo" as const,
      src: "/images/media/0BAA0EF7-D639-4637-800B-F429EF242A8C.jpg",
    },
    {
      id: "photo-3",
      type: "photo" as const,
      src: "/images/media/74E89B41-C909-44E7-82DE-A0D40F236C93.jpg",
    },
    {
      id: "photo-4",
      type: "photo" as const,
      src: "/images/media/DSC07880.jpeg",
    },
    {
      id: "photo-5",
      type: "photo" as const,
      src: "/images/media/DSC07929.jpeg",
    },
    {
      id: "photo-6",
      type: "photo" as const,
      src: "/images/media/DSC07968.jpeg",
    },
    {
      id: "photo-7",
      type: "photo" as const,
      src: "/images/media/DSC07971.jpeg",
    },
    {
      id: "photo-8",
      type: "photo" as const,
      src: "/images/media/IMG_0875.jpeg",
    },
    {
      id: "photo-9",
      type: "photo" as const,
      src: "/images/media/IMG_1125.JPG",
    },
    {
      id: "photo-10",
      type: "photo" as const,
      src: "/images/media/IMG_4316.jpeg",
    },
    {
      id: "photo-11",
      type: "photo" as const,
      src: "/images/media/IMG_9659.jpeg",
    },
    {
      id: "photo-12",
      type: "photo" as const,
      src: "/images/media/MDP 5.jpeg",
    },
    {
      id: "photo-13",
      type: "photo" as const,
      src: "/images/media/Small Biz 10.jpeg",
    },
    {
      id: "photo-14",
      type: "photo" as const,
      src: "/images/media/Small Biz 14.jpeg",
    },
    {
      id: "photo-15",
      type: "photo" as const,
      src: "/images/media/att.Z4F3abSZ0iCMCR7waGRXBt98MCfbZePA3AQTtDLUQmA.jpg",
    },
    {
      id: "photo-16",
      type: "photo" as const,
      src: "/images/media/att.pBJbKGfKmW_-UD12BUkBfwmu35nSbDlTMbQ5a7dutFo.jpg",
    },
    {
      id: "photo-17",
      type: "photo" as const,
      src: "/images/media/att.vMT7vl0bLJFyXpDfThP6rfdCtsG5BmlzlDej3BMl0eo.jpg",
    },
    {
      id: "photo-18",
      type: "photo" as const,
      src: "/images/media/3A0B3FE1-7B33-49FC-9DC4-ABAA9935303A.jpg",
    },
    {
      id: "photo-19",
      type: "photo" as const,
      src: "/images/media/53045505405_96a6c30009_b.jpeg",
    },
    {
      id: "photo-20",
      type: "photo" as const,
      src: "/images/media/79ecfff7-2bec-48e2-ab8c-134fe71f9902.jpg",
    },
    {
      id: "photo-21",
      type: "photo" as const,
      src: "/images/media/DD055DC6-DBE0-4142-ABCE-B2B70B2A6D43.jpg",
    },
    {
      id: "photo-22",
      type: "photo" as const,
      src: "/images/media/IMG_0089.JPG",
    },
    {
      id: "photo-23",
      type: "photo" as const,
      src: "/images/media/IMG_0095.jpeg",
    },
    {
      id: "photo-24",
      type: "photo" as const,
      src: "/images/media/IMG_0755.JPG",
    },
    {
      id: "photo-25",
      type: "photo" as const,
      src: "/images/media/IMG_1250.JPG",
    },
    {
      id: "photo-26",
      type: "photo" as const,
      src: "/images/media/IMG_1723.JPG",
    },
    {
      id: "photo-27",
      type: "photo" as const,
      src: "/images/media/IMG_2265.jpg",
    },
    {
      id: "photo-28",
      type: "photo" as const,
      src: "/images/media/IMG_2479.JPG",
    },
    {
      id: "photo-29",
      type: "photo" as const,
      src: "/images/media/IMG_3510.JPG",
    },
    {
      id: "photo-30",
      type: "photo" as const,
      src: "/images/media/IMG_3511.JPG",
    },
    {
      id: "photo-31",
      type: "photo" as const,
      src: "/images/media/IMG_3514.JPG",
    },
    {
      id: "photo-32",
      type: "photo" as const,
      src: "/images/media/IMG_3601.JPG",
    },
    {
      id: "photo-33",
      type: "photo" as const,
      src: "/images/media/IMG_3984.jpg",
    },
    {
      id: "photo-34",
      type: "photo" as const,
      src: "/images/media/IMG_4051.JPG",
    },
    {
      id: "photo-35",
      type: "photo" as const,
      src: "/images/media/IMG_4052.JPG",
    },
    {
      id: "photo-36",
      type: "photo" as const,
      src: "/images/media/IMG_4053.JPG",
    },
    {
      id: "photo-37",
      type: "photo" as const,
      src: "/images/media/IMG_4089.JPG",
    },
    {
      id: "photo-38",
      type: "photo" as const,
      src: "/images/media/IMG_4099.JPG",
    },
    {
      id: "photo-39",
      type: "photo" as const,
      src: "/images/media/IMG_4551.JPG",
    },
    {
      id: "photo-40",
      type: "photo" as const,
      src: "/images/media/IMG_7715.jpeg",
    },
    {
      id: "photo-41",
      type: "photo" as const,
      src: "/images/media/IMG_7747.JPG",
    },
    {
      id: "photo-42",
      type: "photo" as const,
      src: "/images/media/IMG_8395.JPG",
    },
    {
      id: "photo-43",
      type: "photo" as const,
      src: "/images/media/IMG_8760.jpeg",
    },
    {
      id: "photo-44",
      type: "photo" as const,
      src: "/images/media/IMG_9656.jpeg",
    },
    {
      id: "photo-45",
      type: "photo" as const,
      src: "/images/media/Resized_20230513_125258.jpeg",
    },
    {
      id: "photo-46",
      type: "photo" as const,
      src: "/images/media/IMG_5487.JPG",
    },
    {
      id: "photo-47",
      type: "photo" as const,
      src: "/images/media/IMG_8947.PNG",
    },
    {
      id: "file-1",
      type: "file" as const,
      src: "/images/media/Calloway NMRCC.pdf",
      title: "Northern Midwest Regional Council of Carpenters Endorsement",
      description: "Endorsement letter from the Northern Midwest Regional Council of Carpenters",
      date: "June 2, 2026",
    },
    {
      id: "video-1",
      title: "2026 Candidate Interview: Candace Calloway for State Representative District 5",
      type: "video" as const,
      src: "https://www.youtube.com/embed/qSo6OWF05Ag",
      thumbnail: "/images/media/2026 Candidate Interview.jpg",
      description: "Meet Candace - a comprehensive interview about her vision for District 5.",
      date: "May 2026",
    },
    {
      id: "video-2",
      title: "Campaign Video",
      type: "video" as const,
      src: "/images/media/64195235-E31B-4FD1-9A18-606490A765ED.mp4",
      thumbnail: "/images/media/64195235-E31B-4FD1-9A18-606490A765ED-thumb.jpg",
      description: "Campaign event coverage from District 5.",
      date: "June 2026",
    },
    {
      id: "video-3",
      title: "Campaign Highlight",
      type: "video" as const,
      src: "/images/media/IMG_7596.mp4",
      thumbnail: "/images/media/IMG_7596-thumb.jpg",
      description: "Highlights from recent campaign activities.",
      date: "June 2026",
    },
  ],
  endorsements: {
    confirmed: [
      { name: "Regina Weiss", title: "Incumbent State Representative, District 5", photo: "/images/endorsements/Regina-Weiss.JPG" },
      { name: "Donna Squalls", title: "Royal Oak Township Supervisor", photo: "/images/endorsements/Donna-Squalls.JPG" },
      { name: "Marian McClellan", title: "Oak Park Mayor", photo: "/images/endorsements/Marian-McClellan.JPG" },
      { name: "Angela Whitfield-Calloway", title: "City of Detroit Councilmember", photo: "/images/endorsements/angela-whitfield-calloway.JPG" },
      { name: "Natalie Price", title: "State Representative - District 6", photo: "/images/endorsements/Natalie-Price.JPG" },
      { name: "Julie Edgar", title: "Mayor Pro Tem - Oak Park", photo: "/images/endorsements/Julie-Edgar.JPG" },
      { name: "The Black Slate", title: "", photo: "/images/endorsements/the-black-slate.JPG" },
      { name: "Run for Something", title: "", photo: "/images/endorsements/run-for-something.jpg" },
      { name: "Jessica Newman", title: "Ferndale Board of Education", photo: "/images/endorsements/Jessica-Newman.JPG" },
      { name: "Glenda Stainback", title: "", photo: "/images/endorsements/Glenda-Stainback.JPG" },
      { name: "MI List", title: "", photo: "/images/endorsements/mi-list.JPG"},
      { name: "Paige Mattison", title: "President of Oak Park Board of Education", photo: "/images/endorsements/Paige-Mattison.JPG" },
      { name: "Heather Perryman Tanks", title: "Treasurer of Oak Park Board of Education", photo: "/images/endorsements/heather-perryman-tanks.JPG" },
      { name: "Fannie Lou Hamer PAC", title: "", photo: "/images/endorsements/Fannie-Lou-Hamer-PAC.JPG" },
      { name: "Buzz Thomas", title: "Former Michigan Legislator", photo: "/images/endorsements/buzz-thomas.JPG" },
      { name: "Darryl Woods", title: "Detroit Police Commissioner At-Large", photo: "/images/endorsements/Darryl-Woods.JPG" },
      { name: "IBEW Local 58", title: "", photo: "/images/endorsements/IBEW-Local-58.JPG" },
      { name: "Planned Parenthood Advocates of Michigan", title: "", photo: "" },
      { name: "Young Democrats of Michigan", title: "", photo: "/images/endorsements/Young-Democrats-of-Michigan.png" },
      {name: "Northern Midwest Regional Council of Carpenters", title: "", photo: "/images/endorsements/Northern-Midwest-Regional-Council-of-Carpenters.JPG"},
      { name: "American Federation of State County and Municipal Employees", title: "", photo: "/images/endorsements/AFSCME.JPG" },
      { name: "Fems For Dems", title: "", photo: "/images/endorsements/Fems for Dems.JPG" },
    ],
    includeLucy: false,
  },
} as const;

export type Theme = typeof theme;
export type Pillar = Theme['issues']['pillars'][number];
